version: '3'

services:
  database:
    image: postgres:11.12
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres-password
    volumes:
      - ~/.docker/mentoring-rails/postgres/data:/var/lib/postgresql/data:rw

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres-password
    links:
      - database
    volumes:
      - '.:/home/rails'
    ports:
      - 3000:3000
    restart: always
